version: '3.9'

services:
  app:
    build: .
    container_name: sipa-api
    env_file:
      - .env
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:15
    container_name: sipa-db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:

  